language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8

sudo: required

services:
  - docker

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/tkachuko-blog/backend;
    fi