language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.7

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test && sbt ++$TRAVIS_SCALA_VERSION coverageReport && sbt ++$TRAVIS_SCALA_VERSION coverageReport
after_success:
  - sbt coveralls